name: flix_id
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  cloud_firestore: ^5.0.2
  custom_lint: ^0.6.4
  dio: ^5.4.3+1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: 2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/
